language: node_js
node_js:
   - '8'

branches:
   only:
      - master
      - /^greenkeeper/.*$/

before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
  - npm run-script build_production

deploy:
   provider: firebase
   token: $FIREBASE_TOKEN
   skip_cleanup: true
   on:
      branch: master
